# Generated by Django 5.2.6 on 2025-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_initial_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Format: YYYY-YYYY', max_length=20, null=True),
        ),
    ]
