# Generated by Django 5.2.6 on 2025-10-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('course_code', 'year', 'academic_year')},
        ),
    ]
