# Generated by Django 5.2.6 on 2025-10-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreport',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pendingreport',
            name='course_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pendingreport',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pendingreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reports', to='core.student'),
        ),
        migrations.AlterUniqueTogether(
            name='pendingreport',
            unique_together={('student', 'academic_year', 'year')},
        ),
    ]
