# Generated by Django 5.2.6 on 2025-10-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pendingreport_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerecord',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
