# Generated by Django 5.2.6 on 2025-10-17 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_issuerecord_academic_year_issuerecord_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentItemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requirements', to='core.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_requirements', to='core.item')),
            ],
            options={
                'unique_together': {('department', 'item')},
            },
        ),
    ]
