# Generated by Cascade on 2025-10-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_approval_and_helpcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='help_center/'),
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='helpmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
