# Generated by Django 5.2.6 on 2025-10-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_inventory_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceipt',
            name='consumed_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocklogentry',
            name='pending_delta',
            field=models.IntegerField(default=0),
        ),
    ]
