# Generated by Django 5.2.6 on 2025-10-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0017_inventoryreceipt_consumed_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'admin'), ('username', 'admin')), models.Q(('role', 'admin'), _negated=True), _connector='OR'), name='only_super_admin_can_be_admin'),
        ),
    ]
