# Generated by Django 5.2.6 on 2025-10-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='only_super_admin_can_be_admin',
        ),
    ]
