# Generated by Django 5.2.6 on 2025-10-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmessage',
            name='is_admin_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='is_user_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
