# Generated by Django 5.2.6 on 2025-10-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
