# Generated by Django 5.2.6 on 2025-10-30 16:10

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_default_users'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
    ]
